# Generated by Django 4.0.3 on 2022-03-07 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dispatch_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('employee_number', models.CharField(max_length=4)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='dispatch_name_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('employee_number', models.CharField(max_length=4)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Srdatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('workorder', models.CharField(max_length=12)),
                ('serivce_tag', models.CharField(max_length=7)),
                ('action_taken', models.CharField(choices=[('auto', 'auto'), ('manual', 'manual'), ('deny', 'deny')], default='auto', max_length=10)),
                ('dispatch_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Srlistofdispatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_number', models.CharField(max_length=12)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('serivce_tag', models.CharField(max_length=7)),
                ('action_taken', models.CharField(choices=[('auto', 'auto'), ('manual', 'manual'), ('deny', 'deny')], default='auto', max_length=10)),
                ('dispatch_name_of_sr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainserver.dispatch_name_1')),
            ],
        ),
    ]
