# Generated by Django 4.0.3 on 2022-03-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dispatch_name',
        ),
        migrations.DeleteModel(
            name='Srdatabase',
        ),
    ]
